version: '3.9'

services:
  web:
    build: .
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn app.main:app --reload --host 0.0.0.0'
    volumes:
      - .:/app
    ports:
      - 8008:8000
    environment:
      - DATABASE_URL=postgresql://fastapi1:fastapi1@localhost:5432/db
    depends_on:
      - db
  db:
    image: postgres
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=fastapi1
      - POSTGRES_PASSWORD=fastapi1
      - POSTGRES_DB=db
      - POSTGRES_SERVER=localhost
      - POSGRES_HOST_AUTH_METHOD=trust

  pg_admin:
    image: dpage/pgadmin4
    container_name: pg_admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports: 
      - 80:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=fastapi1@admin.com
      - PGADMIN_DEFAULT_PASSWORD=fastapi1
      - PGADMIN_LISTEN_PORT=80
    links:
      - "db:pgsql-server"

volumes:
  postgres_data:
  pgadmin_data: